### ISSUE TITLE
not working correctly on lockscreen

### ISSUE THREAD

**Issue by Phoenix09** [Nephiel/NFCLockScreenOffEnablerMM#3]
I only hear the tag start sound, never the tag end sound, and Trigger never sees it  
using the instructions in the thread for the original module to modify NciNci.apk for lockscreen works fine, but with unmodified apk and this module it doesn't. 
this is on a Galaxy S6 running 6.0.1

will get a debug log later

**Comment by Phoenix09** [comment]
actually I get the error sound, only on lockscreen.
[xposed_error_20160418_040849.txt](https://github.com/Nephiel/NFCLockScreenOffEnablerMM/files/223033/xposed_error_20160418_040849.txt)
[stock NfcNci.apk](https://mega.nz/#!txgimJrC!UF4gaFuHhZhtVlG95vkov8g4qB-LWXYSNuytOcTmbCY)

it would be nice if it could be fixed, but it's not much of a problem as I have a modded apk that works fine.

**Comment by Nephiel** [comment]
I don't see the problem in the log, it appears to be reading the tags fine... I only use this module to disable the sounds and get around [this android bug](https://code.google.com/p/android/issues/detail?id=79928) in order to get Smart Lock to work. The modded APK may be more suited to your purpose.
